services:
    api:
      build: api
      command: npm start
      volumes:
        - ./api:/usr/src/app
        - /usr/src/app/node_modules
      restart: always
      ports:
        - 5000:5000
    site:
      build: site
      command: npm start
      volumes:
        - ./site:/usr/src/app
        - /usr/src/app/node_modules
      restart: always
      ports:
        - 3000:3000
